### ISSUE TITLE
Script Error can't get application process "Control Center"

### ISSUE THREAD

**Issue by lostdesign** [x74353/KeyJerk-Reactions#2]
I downloaded the script today and executed it (accessibility controls had been granted). When executing the script, it throws "can't get application process "Control Center".

Running on Sonoma 14.5 / M1 Pro

![Screenshot 2024-06-20 at 10 40 46](https://github.com/x74353/KeyJerk-Reactions/assets/5164617/6b2ca528-66b7-4e8d-a6c7-81fac123a4e8)

**Comment by x74353** [comment]
@lostdesign, thanks for reporting this issue. I've discontinued support for the AppleScript version of KeyJerk Reactions. I've just uploaded a dmg for version 2.0, which is now a scriptable app. 

Example:
`tell application "KeyJerk Reactions" to react with "Thumbs-up"`

Hopefully the KeyJerk Reactions solves this error for you.
